spring.application.name=birthweather
spring.datasource.url=jdbc:postgresql://localhost:5432/birthweather
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update